require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Mailer links must land on the app host (host-role enforcement is on in dev
  # too — config.x.app_host defaults to app.localhost): circles, sign-in, and
  # settings only route there. Bare localhost 404s them.
  config.action_mailer.default_url_options = { host: "app.localhost", port: 3020 }

  # Open sent mail (e.g. magic-link sign in) in the browser instead of delivering it.
  config.action_mailer.delivery_method = :letter_opener

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Dev mirrors production's host-role routing (ADR 0018/0019) out of the box:
  # browsers resolve *.localhost to loopback natively, so the admin lives at
  # app.localhost:3020/{SLUG}/admin/… and 127.0.0.1/localhost act as a tenant
  # host serving the first account's public site. APP_HOST in the environment
  # still wins; set it to the empty string to force single-tenant legacy mode.
  config.x.app_host = ENV.fetch("APP_HOST", "app.localhost")

  # Allow the platform sites host so a domain-less account's public site is
  # browsable in dev at sites.kindredquill.com:3020/{slug} (the screenshot
  # runner maps the hostname to loopback inside its browser). Any account,
  # not just Account.first — the tenant-host fallback only reaches the latter.
  config.hosts << ENV.fetch("CF_CNAME_TARGET", "sites.kindredquill.com")
end
